In [1]:
# with sys we adding the folders in the execution path
import sys
sys.path.insert(0, '../')

#modules for numerical representations
from numerical_representation_strategies.physicochemical_properties import physicochemical_encoder
from numerical_representation_strategies.constant_values import constant_values

#pandas
import pandas as pd

In [2]:
df_data = pd.read_csv("../../dataset_examples/demo_df_sequences.csv")

In [3]:
# The property with id ANDN920101 will be used, in the case of the use of topics, please use properties like "Group_XXX", See the inputs encoders for more details.
property_to_use = 'ANDN920101'
encoders = pd.read_csv("../../inputs_encoder/aaindex_encoders.csv")
encoders.index = encoders['residue']

column_with_seq = 'sequence'#the name of column with the sequence in the dataset to process
column_with_response = 'm'#select the response column, only for demostration we are using this column

In [4]:
print("Instance object")
encoding_instance = physicochemical_encoder(df_data,
                 property_to_use,
                 encoders,
                 constant_values(),
                 column_with_seq,
                 column_with_response)

Instance object

In [5]:
df_data_encoding = encoding_instance.encoding_dataset()
df_data_encoding

Processing results
Creating dataset
Export dataset

,m,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_288,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297
0,0,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
1,1,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
2,1,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
3,1,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
4,1,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
77,3,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
78,3,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
79,3,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
80,4,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5

In [9]:
from deep_learning_architectures.models import Models
from training_classic_ml.class_ml_models import classification_models

response_column = df_data_encoding['m']
df_data_to_train = df_data_encoding.drop(columns=['m'])

class_models = classification_models(df_data_to_train, response_column)
X_train, X_test, y_train, y_test = class_models.split_to_train(test_size=0.2)

In [10]:
import numpy as np

#("binary", "classification", "regression") -> task

labels = np.array(list(set(response_column)))
models = Models(X_train, y_train, X_test, y_test, labels, "classification", "demo")

In [11]:
models.fit_models(10, 1)

Epoch 1/10
2/2 [==============================] - 7s 9ms/step - loss: 1.9384
Epoch 2/10
2/2 [==============================] - 0s 5ms/step - loss: 1.1766
Epoch 3/10
2/2 [==============================] - 0s 6ms/step - loss: 1.1120
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 1.1140
Epoch 5/10
2/2 [==============================] - 0s 8ms/step - loss: 1.0692
Epoch 6/10
2/2 [==============================] - 0s 6ms/step - loss: 1.0219
Epoch 7/10
2/2 [==============================] - 0s 11ms/step - loss: 1.0071
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 1.0084
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 0.9881
Epoch 10/10
2/2 [==============================] - 0s 6ms/step - loss: 0.9744

In [13]:
metrics = models.get_metrics()
metrics

2/2 [==============================] - 0s 4ms/step
1/1 [==============================] - 0s 35ms/step

{'arquitecture': 'demo',
 'trainable_params': 38933,
 'non_trainable_params': 0,
 'labels': [0, 1, 2, 3, 4],
 'train_metrics': {'accuracy': 0.671875,
  'recall': 0.671875,
  'precision': 0.671875,
  'f1_score': 0.671875,
  'mcc': 0.0,
  'confusion_matrix': [[43, 0, 0, 0],
   [4, 0, 0, 0],
   [5, 0, 0, 0],
   [12, 0, 0, 0]]},
 'test_metrics': {'accuracy': 0.5294117647058824,
  'recall': 0.5294117647058824,
  'precision': 0.5294117647058824,
  'f1_score': 0.5294117647058824,
  'mcc': 0.0,
  'confusion_matrix': [[0, 1, 0, 0, 0],
   [0, 9, 0, 0, 0],
   [0, 2, 0, 0, 0],
   [0, 2, 0, 0, 0],
   [0, 3, 0, 0, 0]],
  'roc_auc_score': 0.4271825396825397}}