In [2]:
import sys
sys.path.insert(0, '../')
from numerical_representation_strategies.physicochemical_properties import physicochemical_encoder
from numerical_representation_strategies.fft_encoding import fft_encoding
from numerical_representation_strategies.constant_values import constant_values

import pandas as pd

In [3]:
df_data = pd.read_csv("../../dataset_examples/demo_df_sequences.csv")
df_data

,name,sequence,peak,is_train,m
0,parent,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,539,True,0
1,W122A,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,510,True,1
2,W122G,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,510,True,1
3,W122R,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,519,True,1
4,V126A,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,525,True,1
...,...,...,...,...,...
76,T125C/W222M,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,562,True,2
77,D121E/T125C/A256M,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,620,False,3
78,T125C/F185T/A256M,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,597,False,3
79,W122G/T125C/A256M,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,510,False,3
80,D121E/T125C/F185T/A256M,MLMTVFSSAPELALLGSTFAQVDPSNLSVSDSLTYGQFNLVYNAFS...,622,False,4

In [4]:
property_to_use = 'ANDN920101'
encoders = pd.read_csv("../../inputs_encoder/aaindex_encoders.csv")
encoders.index = encoders['residue']

column_with_seq = 'sequence'
column_with_response = 'peak'

In [5]:
print("Instance object")
encoding_instance = physicochemical_encoder(df_data,
                 property_to_use,
                 encoders,
                 constant_values(),
                 column_with_seq,
                 column_with_response)

Instance object

In [6]:
df_data_encoding = encoding_instance.encoding_dataset()
df_data_encoding

Processing results
Creating dataset
Export dataset

,peak,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_288,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297
0,539,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
1,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
2,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
3,519,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
4,525,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,562,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
77,620,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
78,597,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
79,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
80,622,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5

In [7]:
response_column = df_data_encoding['peak']
df_data_to_train = df_data_encoding.drop(columns=['peak'])

In [10]:
from training_classic_ml.regx_ml_models import regression_models

regx_models = regression_models(df_data_to_train, response_column)
X_train, X_test, y_train, y_test = regx_models.split_to_train(test_size=0.2)

regx_models.apply_model(X_train=X_train, y_train=y_train, option=1)

performances = regx_models.get_performances(X_test=X_test, y_test=y_test)

performances

{'r2_score': 0.8746754988493693,
 'mean absolute error': 9.587058823529409,
 'mean squared error': 148.86729411764705}