In [1]:
# with sys we adding the folders in the execution path
import sys
sys.path.insert(0, '../')

#modules for numerical representations
from numerical_representation_strategies.physicochemical_properties import physicochemical_encoder
from numerical_representation_strategies.constant_values import constant_values

#pandas
import pandas as pd

In [2]:
df_data = pd.read_csv("../../dataset_examples/demo_df_sequences.csv")

In [3]:
# The property with id ANDN920101 will be used, in the case of the use of topics, please use properties like "Group_XXX", See the inputs encoders for more details.
property_to_use = 'ANDN920101'
encoders = pd.read_csv("../../inputs_encoder/aaindex_encoders.csv")
encoders.index = encoders['residue']

column_with_seq = 'sequence'#the name of column with the sequence in the dataset to process
column_with_response = 'peak'#select the response column, only for demostration we are using this column

In [4]:
print("Instance object")
encoding_instance = physicochemical_encoder(df_data,
                 property_to_use,
                 encoders,
                 constant_values(),
                 column_with_seq,
                 column_with_response)

Instance object

In [5]:
df_data_encoding = encoding_instance.encoding_dataset()
df_data_encoding

Processing results
Creating dataset
Export dataset

,peak,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,...,p_288,p_289,p_290,p_291,p_292,p_293,p_294,p_295,p_296,p_297
0,539,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
1,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
2,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
3,519,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
4,525,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,562,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
77,620,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
78,597,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
79,510,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5
80,622,4.52,4.17,4.52,4.35,3.95,4.66,4.5,4.5,4.35,...,4.35,4.75,4.36,4.5,3.97,3.97,4.5,4.17,3.95,4.5

In [6]:
from deep_learning_architectures.models import Models
from training_classic_ml.class_ml_models import classification_models

response_column = df_data_encoding['peak']
df_data_to_train = df_data_encoding.drop(columns=['peak'])

class_models = classification_models(df_data_to_train, response_column)
X_train, X_test, y_train, y_test = class_models.split_to_train(test_size=0.2)

In [7]:
import numpy as np

#("binary", "classification", "regression") -> task

labels = np.array(list(set(response_column)))
models = Models(X_train, y_train, X_test, y_test, labels, "regression", "demo")

In [8]:
models.fit_models(10, 1)

Epoch 1/10
2/2 [==============================] - 3s 7ms/step - loss: 279885.1250
Epoch 2/10
2/2 [==============================] - 0s 10ms/step - loss: 277367.3750
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 275006.7500
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 273087.8750
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 271768.0000
Epoch 6/10
2/2 [==============================] - 0s 10ms/step - loss: 270968.0000
Epoch 7/10
2/2 [==============================] - 0s 8ms/step - loss: 270536.1875
Epoch 8/10
2/2 [==============================] - 0s 6ms/step - loss: 270293.9688
Epoch 9/10
2/2 [==============================] - 0s 6ms/step - loss: 270122.8750
Epoch 10/10
2/2 [==============================] - 0s 7ms/step - loss: 269973.3750

In [9]:
metrics = models.get_metrics()
metrics

2/2 [==============================] - 0s 4ms/step
1/1 [==============================] - 0s 182ms/step

{'arquitecture': 'demo',
 'trainable_params': 38673,
 'non_trainable_params': 0,
 'train_metrics': {'mse': 269864.82462757046,
  'mae': 518.2952916175127,
  'r2_score': -217.5469058130876,
  'kendalltau': KendalltauResult(correlation=-0.2438471031198693, pvalue=0.005308651828917631),
  'pearsonr': PearsonRResult(statistic=array([-0.6558193250603346], dtype=object), pvalue=4.058917445846955e-09),
  'spearmanr': SpearmanrResult(correlation=-0.4014911573317713, pvalue=0.0010084748579664426)},
 'test_metrics': {'mse': 258919.77448416644,
  'mae': 507.67304308274214,
  'r2': -216.97260283120423,
  'kendalltau': KendalltauResult(correlation=-0.5278846884821402, pvalue=0.0033666490826811586),
  'pearsonr': PearsonRResult(statistic=array([-0.7092149719749465], dtype=object), pvalue=0.0014323425030100003),
  'spearmanr': SpearmanrResult(correlation=-0.6580725610722443, pvalue=0.004082011634682458)}}